<!-- ...................................................................... -->
<!-- aavocab AAs and Face Marks Module .................................... -->
<!-- file: aavocab-aa.mod
     
     This is the "aavocab", as defined by 16
     <http://pc5.2ch.net/test/read.cgi/hp/1096723178/16>.
     
     Copyright 2010 Wakaba <w@suika.fam.cx>, All Rights Reserved.
     
     Permission to use, copy, modify and distribute this DTD and its
     accompanying documentation for any purpose and without fee is hereby
     granted in perpetuity, provided that the above copyright notice and
     this paragraph appear in all copies.  The copyright holders make no
     representation about the suitability of the DTD for any purpose.
     
     It is provided "as is" without expressed or implied warranty.
     
     Revision: 2010-06-20T04:56:41+00:00 (Generated by mkdtds/1.7)
     
     This DTD module is identified by the SYSTEM identifier:
     
       SYSTEM "http://suika.fam.cx/www/markup/2004/aavocab/schema/aavocab-aa.mod"
     
     ...................................................................... -->

<!-- AAs and Face Marks

       aa
-->

<!-- aa: aa要素の内容は文字列であるが、それは経験に現れた現象としての物でなくて、
     そうした現象と独立にそれ自体としてあると考えられた物としてインスタンス化される。
     これは我々の感官を触発して、直観の形式の助けを借りてレンダリングを生じさせるが、
     それ自体がどんなものであるかは我々には不可知であるとする。
     
     <http://pc5.2ch.net/test/read.cgi/hp/1096723178/19>
     
     Example:
       <aa xmlns="http://pc5.2ch.net/test/read.cgi/hp/1096723178/aavocab#">orz</aa>  -->

<!ENTITY % aavocab.aa.element "INCLUDE">
<![%aavocab.aa.element;[
<!ENTITY % aavocab.aa.content "(#PCDATA|%Inline.mix;)*">
<!ENTITY % aavocab.aa.qname "aa">
<!ENTITY % aavocab.aa.tagmin.start "-">
<!ENTITY % aavocab.aa.tagmin.end "-">
<![%sgml.tag.minimizable;[
<!ENTITY % aavocab.aa.tagmin "%aavocab.aa.tagmin.start; %aavocab.aa.tagmin.end;">
<!-- end of sgml.tag.minimizable -->]]>
<!ENTITY % aavocab.aa.tagmin "">
<!ELEMENT %aavocab.aa.qname; %aavocab.aa.tagmin; %aavocab.aa.content;>
<!-- end of aavocab.aa.element -->]]>

<!ENTITY % aavocab.aa.attlist "INCLUDE">
<![%aavocab.aa.attlist;[
<!ATTLIST %aavocab.aa.qname;
	xml:lang	%LanguageCode.datatype;	#IMPLIED
	xml:base	%URI.datatype;	#IMPLIED
	xml:space	(default|preserve)	#IMPLIED
	%XSI.prefix;:schemaLocation CDATA #IMPLIED
	%XSI.prefix;:type NMTOKEN #IMPLIED
	%XSI.prefix;:nil (true|false|1|0) #IMPLIED
	%aavocab.common.attrib;>
<!-- end of aavocab.aa.attlist -->]]>


<!-- end of aavocab-aa.mod -->
