<!-- ...................................................................... -->
<!-- XJDCM (Based on JIS X 4052:2000) Text Module ......................... -->
<!-- file: jdcm-text.mod
     
     This is XJDCM, an XML representation of JDCM
     ("Exchange format for Japanese documents with composition markup").
     
     Copyright 2010 Wakaba <w@suika.fam.cx>, All Rights Reserved.
     
     Permission to use, copy, modify and distribute this DTD and its
     accompanying documentation for any purpose and without fee is hereby
     granted in perpetuity, provided that the above copyright notice and
     this paragraph appear in all copies.  The copyright holders make no
     representation about the suitability of the DTD for any purpose.
     
     It is provided "as is" without expressed or implied warranty.
     
     Revision: 2010-06-20T04:48:31+00:00 (Generated by mkdtds/1.7)
     
     This DTD module is identified by the SYSTEM identifier:
     
       SYSTEM "data:,jdcm-dtd-module-jdcm-text.mod"
     
     ...................................................................... -->

<!-- Text

       ch
-->

<!-- ch: Specific glyph of character [JIS X 4052:2000, 6.2 b) 1.2)]
     Content shall be an alternative text.  -->

<!ENTITY % jdcm.ch.element "INCLUDE">
<![%jdcm.ch.element;[
<!ENTITY % jdcm.ch.content "(#PCDATA)*">
<!ENTITY % jdcm.ch.qname "ch">
<!ENTITY % jdcm.ch.tagmin.start "-">
<!ENTITY % jdcm.ch.tagmin.end "-">
<![%sgml.tag.minimizable;[
<!ENTITY % jdcm.ch.tagmin "%jdcm.ch.tagmin.start; %jdcm.ch.tagmin.end;">
<!-- end of sgml.tag.minimizable -->]]>
<!ENTITY % jdcm.ch.tagmin "">
<!ELEMENT %jdcm.ch.qname; %jdcm.ch.tagmin; %jdcm.ch.content;>
<!-- end of jdcm.ch.element -->]]>

<!ENTITY % jdcm.ch.attlist "INCLUDE">
<![%jdcm.ch.attlist;[
<!ATTLIST %jdcm.ch.qname;
	height	%jdcm.position.datatype;	#IMPLIED
	left	%jdcm.position.datatype;	"0"
	src	%URI.datatype;	#REQUIRED
	top	%jdcm.position.datatype;	"0"
	width	%jdcm.position.datatype;	#IMPLIED
	%jdcm.subbody.attrib;
	%jdcm.common.attrib;>
<!-- end of jdcm.ch.attlist -->]]>


<!-- end of jdcm-text.mod -->
