<!-- ...................................................................... -->
<!-- XJDCM (Based on JIS X 4052:2000) Common Attributes Module ............ -->
<!-- file: jdcm-attribs.mod
     
     This is XJDCM, an XML representation of JDCM
     ("Exchange format for Japanese documents with composition markup").
     
     Copyright 2010 Wakaba <w@suika.fam.cx>, All Rights Reserved.
     
     Permission to use, copy, modify and distribute this DTD and its
     accompanying documentation for any purpose and without fee is hereby
     granted in perpetuity, provided that the above copyright notice and
     this paragraph appear in all copies.  The copyright holders make no
     representation about the suitability of the DTD for any purpose.
     
     It is provided "as is" without expressed or implied warranty.
     
     Revision: 2010-06-20T04:48:31+00:00 (Generated by mkdtds/1.7)
     
     This DTD module is identified by the SYSTEM identifier:
     
       SYSTEM "data:,jdcm-dtd-module-jdcm-attribs.mod"
     
     ...................................................................... -->

<!-- Common Attributes

     This module declares many of the common attributes.
-->

<!ENTITY % jdcm.common.extra.attrib "">

<!-- Attributes for "文書中の要素の部分集合要素" -->
<!ENTITY % jdcm.subsetelement.attrib
	"class	%jdcm.classes.datatype;	#IMPLIED
	id	ID	#IMPLIED">

<!-- Attributes for body and its subset elements -->
<!ENTITY % jdcm.subbody.attrib
	"%jdcm.subsetelement.attrib;
	style	%jdcm.StyleSheet.datatype;	#IMPLIED">

<!ENTITY % jdcm.align.attrib
	'align	(行頭|行末|center|均等)	"行頭"'>

<!ENTITY % jdcm.cellpadding.attrib
	"cellpadding	%jdcm.tablelength.datatype;	#IMPLIED">

<!ENTITY % jdcm.em.attrib
	"%jdcm.subbody.attrib;">

<!ENTITY % jdcm.hn.attrib
	"%jdcm.subbody.attrib;">

<!ENTITY % jdcm.行そろえ.attrib
	'行そろえ	(こま頭|こま中央|こま末|行均等)	"こま中央"'>

<!ENTITY % jdcm.td.attrib
	'%jdcm.align.attrib;
	%jdcm.cellpadding.attrib;
	height	%jdcm.tablelength.datatype;	#IMPLIED
	width	%jdcm.tablelength.datatype;	#IMPLIED
	行こま合成	%jdcm.positiveinteger.datatype;	"1"
	%jdcm.行そろえ.attrib;
	列こま合成	%jdcm.positiveinteger.datatype;	"1"
	%jdcm.subbody.attrib;'>

<!ENTITY % jdcm.common.attrib
	"%jdcm.common.extra.attrib;
	%jdcm.xmlns.attrib;">


<!-- end of jdcm-attribs.mod -->
