all:
	wget -OMessage/Markup/SuikaWikiConfig20/Node.pm http://suika.fam.cx/gate/cvs/*checkout*/messaging/manakai/lib/Message/Markup/SuikaWikiConfig20/Node.pm
	wget -OMessage/Markup/SuikaWikiConfig20/Parser.pm http://suika.fam.cx/gate/cvs/*checkout*/messaging/manakai/lib/Message/Markup/SuikaWikiConfig20/Parser.pm

## License: Public Domain.
