<!-- ...................................................................... -->
<!-- HLink First Working Draft Core Module ................................ -->
<!-- file: hlink-core.mod
     

     
     Copyright 2010 Wakaba <wakaba@suikawiki.org>, All Rights Reserved.
     
     Permission to use, copy, modify and distribute this DTD and its
     accompanying documentation for any purpose and without fee is hereby
     granted in perpetuity, provided that the above copyright notice and
     this paragraph appear in all copies.  The copyright holders make no
     representation about the suitability of the DTD for any purpose.
     
     It is provided "as is" without expressed or implied warranty.
     
     Revision: 2010-06-20T04:51:18+00:00 (Generated by mkdtds/1.7)

     R4.9.18  URLs updated.
     
     This DTD module is identified by the SYSTEM identifier:
     
       SYSTEM "https://suika.suikawiki.org/gate/cvs/*checkout*/markup/hlink/schema/module/hlink-core.mod"
     
     ...................................................................... -->

<!-- Core

       hlink, hlinks
-->

<!-- hlinks ............................................ -->

<!ENTITY % hlink.hlinks.element "INCLUDE">
<![%hlink.hlinks.element;[
<!ENTITY % hlink.hlinks.content "(%hlink.hlink.qname;)+">
<!ENTITY % hlink.hlinks.qname "hlinks">
<!ENTITY % hlink.hlinks.tagmin.start "-">
<!ENTITY % hlink.hlinks.tagmin.end "-">
<![%sgml.tag.minimizable;[
<!ENTITY % hlink.hlinks.tagmin "%hlink.hlinks.tagmin.start; %hlink.hlinks.tagmin.end;">
<!-- end of sgml.tag.minimizable -->]]>
<!ENTITY % hlink.hlinks.tagmin "">
<!ELEMENT %hlink.hlinks.qname; %hlink.hlinks.tagmin; %hlink.hlinks.content;>
<!-- end of hlink.hlinks.element -->]]>

<!ENTITY % hlink.hlinks.attlist "INCLUDE">
<![%hlink.hlinks.attlist;[
<!ATTLIST %hlink.hlinks.qname;
	%hlink.common.attrib;>
<!-- end of hlink.hlinks.attlist -->]]>

<!-- hlink ............................................. -->

<!ENTITY % hlink.hlink.element "INCLUDE">
<![%hlink.hlink.element;[
<!ENTITY % hlink.hlink.content "EMPTY">
<!ENTITY % hlink.hlink.qname "hlink">
<!ENTITY % hlink.hlink.tagmin.start "-">
<!ENTITY % hlink.hlink.tagmin.end "o">
<![%sgml.tag.minimizable;[
<!ENTITY % hlink.hlink.tagmin "%hlink.hlink.tagmin.start; %hlink.hlink.tagmin.end;">
<!-- end of sgml.tag.minimizable -->]]>
<!ENTITY % hlink.hlink.tagmin "">
<!ELEMENT %hlink.hlink.qname; %hlink.hlink.tagmin; %hlink.hlink.content;>
<!-- end of hlink.hlink.element -->]]>

<!ENTITY % hlink.hlink.attlist "INCLUDE">
<![%hlink.hlink.attlist;[
<!ATTLIST %hlink.hlink.qname;
	namespace	%URI.datatype;	#REQUIRED
	element	%hlink.local-name.datatype;	#IMPLIED
	locator	CDATA	#IMPLIED
	effect	CDATA	#IMPLIED
	actuate	CDATA	#IMPLIED
	replacement	CDATA	#IMPLIED
	role	CDATA	#IMPLIED
	reverseRole	CDATA	#IMPLIED
	shape	CDATA	#IMPLIED
	coords	CDATA	#IMPLIED
	arcrole	CDATA	#IMPLIED
	label	CDATA	#IMPLIED
	from	CDATA	#IMPLIED
	to	CDATA	#IMPLIED
	mediaType	CDATA	#IMPLIED
	onSuccess	CDATA	#IMPLIED
	onFailure	CDATA	#IMPLIED
	%hlink.common.attrib;>
<!-- end of hlink.hlink.attlist -->]]>


<!-- end of hlink-core.mod -->
