<!-- ...................................................................... -->
<!-- HLink First Working Draft Datatypes Module ........................... -->
<!-- file: hlink-datatype.mod
     

     
     Copyright 2010 Wakaba <w@suika.fam.cx>, All Rights Reserved.
     
     Permission to use, copy, modify and distribute this DTD and its
     accompanying documentation for any purpose and without fee is hereby
     granted in perpetuity, provided that the above copyright notice and
     this paragraph appear in all copies.  The copyright holders make no
     representation about the suitability of the DTD for any purpose.
     
     It is provided "as is" without expressed or implied warranty.
     
     Revision: 2010-06-20T04:51:18+00:00 (Generated by mkdtds/1.7)
     
     This DTD module is identified by the SYSTEM identifier:
     
       SYSTEM "http://suika.fam.cx/gate/cvs/*checkout*/markup/hlink/schema/module/hlink-datatype.mod"
     
     ...................................................................... -->

<!-- Datatypes

     This module defines containers for the datatypes.
-->

<!-- Internet Media Type [RFC 2046] -->
<!ENTITY % ContentType.datatype "CDATA">

<!-- coordinate *("," coordinate) -->
<!ENTITY % Coords.datatype "CDATA">

<!-- linktype *(WSP linktype) -->
<!ENTITY % LinkTypes.datatype "CDATA">

<!ENTITY % Shape.datatype "(default|rect|circle|poly)">

<!-- A URI Reference -->
<!ENTITY % URI.datatype "CDATA">

<!ENTITY % hlink.local-name.datatype "NMTOKEN">


<!-- end of hlink-datatype.mod -->
