<!-- ...................................................................... -->
<!-- XSL Transformations 1 Datatypes Module ............................... -->
<!-- file: xslt1-datatype.mod
     
     XSLT, XSL Trensformations, Version 1.0
     
     Copyright 2010 Wakaba <w@suika.fam.cx>, All Rights Reserved.
     
     Permission to use, copy, modify and distribute this DTD and its
     accompanying documentation for any purpose and without fee is hereby
     granted in perpetuity, provided that the above copyright notice and
     this paragraph appear in all copies.  The copyright holders make no
     representation about the suitability of the DTD for any purpose.
     
     It is provided "as is" without expressed or implied warranty.
     
     Revision: 2010-06-20T04:26:01+00:00 (Generated by mkdtds/1.7)
     
     This DTD module is identified by the SYSTEM identifier:
     
       SYSTEM "xslt1-datatype.mod"
     
     ...................................................................... -->

<!-- Datatypes

     This module defines containers for the datatypes.
-->

<!-- Internet Media Type [RFC 2046] -->
<!ENTITY % ContentType.datatype "CDATA">

<!-- A URI Reference -->
<!ENTITY % URI.datatype "CDATA">

<!-- An attribute value template that results "alphabetical" or "traditional" -->
<!ENTITY % xslt1.avt-alphabetical-traditional.datatype "CDATA">

<!-- An attribute value template that results "ascending" or "descending" -->
<!ENTITY % xslt1.avt-ascending-descending.datatype "CDATA">

<!-- An attribute value template that results a character -->
<!ENTITY % xslt1.avt-char.datatype "CDATA">

<!-- An attribute value template that results an NCName -->
<!ENTITY % xslt1.avt-ncname.datatype "CDATA">

<!-- An attribute value template that results an NMTOKEN -->
<!ENTITY % xslt1.avt-nmtoken.datatype "CDATA">

<!-- An attribute value template that results a number -->
<!ENTITY % xslt1.avt-number.datatype "CDATA">

<!-- An attribute value template that results a QName -->
<!ENTITY % xslt1.avt-qname.datatype "CDATA">

<!-- An attribute value template that results a string -->
<!ENTITY % xslt1.avt-string.datatype "CDATA">

<!-- An attribute value template that results "text", "number"
     or QName but not NCName -->
<!ENTITY % xslt1.avt-text-number-qname-but-not-ncname.datatype "CDATA">

<!-- An attribute value template that results "upper-first" or "lower-first" -->
<!ENTITY % xslt1.avt-upper-first-lower-first.datatype "CDATA">

<!-- An attribute value template that results a URI reference -->
<!ENTITY % xslt1.avt-uri-reference.datatype "CDATA">

<!-- An XPath expression evaluated as boolean -->
<!ENTITY % xslt1.boolean-expr.datatype "CDATA">

<!ENTITY % xslt1.char.datatype "CDATA">

<!-- An expression -->
<!ENTITY % xslt1.expr.datatype "CDATA">

<!-- An expression evaluated as node-set -->
<!ENTITY % xslt1.node-set-expr.datatype "CDATA">

<!ENTITY % xslt1.number.datatype "NMTOKEN">

<!-- An expression evaluated as number -->
<!ENTITY % xslt1.number-expr.datatype "CDATA">

<!-- A pattern -->
<!ENTITY % xslt1.pattern.datatype "CDATA">

<!-- Namespace prefix or "#default" -->
<!ENTITY % xslt1.prefix-or-default.datatype "CDATA">

<!-- A priority -->
<!ENTITY % xslt1.priority.datatype "CDATA">

<!-- A QName -->
<!ENTITY % xslt1.qname.datatype "NMTOKEN">

<!-- A whitespace-separeted list of QNames -->
<!ENTITY % xslt1.qnames.datatype "NMTOKENS">

<!ENTITY % xslt1.string.datatype "CDATA">

<!ENTITY % xslt1.string-expression.datatype "CDATA">

<!-- A whitespace-separeted list of tokens -->
<!ENTITY % xslt1.tokens.datatype "CDATA">

<!-- "yes" or "no" -->
<!ENTITY % xslt1.yesno.datatype "(yes|no)">


<!-- end of xslt1-datatype.mod -->
