<!-- ...................................................................... -->
<!-- XSL Transformations 1 Expression Module .............................. -->
<!-- file: xslt1-expression.mod
     
     XSLT, XSL Trensformations, Version 1.0
     
     Copyright 2010 Wakaba <w@suika.fam.cx>, All Rights Reserved.
     
     Permission to use, copy, modify and distribute this DTD and its
     accompanying documentation for any purpose and without fee is hereby
     granted in perpetuity, provided that the above copyright notice and
     this paragraph appear in all copies.  The copyright holders make no
     representation about the suitability of the DTD for any purpose.
     
     It is provided "as is" without expressed or implied warranty.
     
     Revision: 2010-06-20T04:26:01+00:00 (Generated by mkdtds/1.7)
     
     This DTD module is identified by the SYSTEM identifier:
     
       SYSTEM "xslt1-expression.mod"
     
     ...................................................................... -->

<!-- Expression

       decimal-format, key
-->

<!-- key: Variable ..................................... -->

<!ENTITY % xslt1.key.element "INCLUDE">
<![%xslt1.key.element;[
<!ENTITY % xslt1.key.content "EMPTY">
<!ENTITY % xslt1.key.qname "key">
<!ENTITY % xslt1.key.tagmin.start "-">
<!ENTITY % xslt1.key.tagmin.end "o">
<![%sgml.tag.minimizable;[
<!ENTITY % xslt1.key.tagmin "%xslt1.key.tagmin.start; %xslt1.key.tagmin.end;">
<!-- end of sgml.tag.minimizable -->]]>
<!ENTITY % xslt1.key.tagmin "">
<!ELEMENT %xslt1.key.qname; %xslt1.key.tagmin; %xslt1.key.content;>
<!-- end of xslt1.key.element -->]]>

<!ENTITY % xslt1.key.attlist "INCLUDE">
<![%xslt1.key.attlist;[
<!ATTLIST %xslt1.key.qname;
	name	%xslt1.qname.datatype;	#REQUIRED
	match	%xslt1.pattern.datatype;	#REQUIRED
	use	%xslt1.expr.datatype;	#REQUIRED
	%xslt1.common.attrib;>
<!-- end of xslt1.key.attlist -->]]>

<!-- decimal-format: Number format ..................... -->

<!ENTITY % xslt1.decimal-format.element "INCLUDE">
<![%xslt1.decimal-format.element;[
<!ENTITY % xslt1.decimal-format.content "EMPTY">
<!ENTITY % xslt1.decimal-format.qname "decimal-format">
<!ENTITY % xslt1.decimal-format.tagmin.start "-">
<!ENTITY % xslt1.decimal-format.tagmin.end "o">
<![%sgml.tag.minimizable;[
<!ENTITY % xslt1.decimal-format.tagmin "%xslt1.decimal-format.tagmin.start; %xslt1.decimal-format.tagmin.end;">
<!-- end of sgml.tag.minimizable -->]]>
<!ENTITY % xslt1.decimal-format.tagmin "">
<!ELEMENT %xslt1.decimal-format.qname; %xslt1.decimal-format.tagmin; %xslt1.decimal-format.content;>
<!-- end of xslt1.decimal-format.element -->]]>

<!ENTITY % xslt1.decimal-format.attlist "INCLUDE">
<![%xslt1.decimal-format.attlist;[
<!ATTLIST %xslt1.decimal-format.qname;
	name	%xslt1.qname.datatype;	#IMPLIED
	decimal-separator	%xslt1.char.datatype;	"."
	grouping-separator	%xslt1.char.datatype;	","
	infinity	%xslt1.string.datatype;	"Infinity"
	minus-sign	%xslt1.char.datatype;	"-"
	NaN	%xslt1.string.datatype;	"NaN"
	percent	%xslt1.char.datatype;	"%"
	per-mille	%xslt1.char.datatype;	"%#x2030;"
	zero-digit	%xslt1.char.datatype;	"0"
	digit	%xslt1.char.datatype;	"#"
	pattern-separator	%xslt1.char.datatype;	";"
	%xslt1.common.attrib;>
<!-- end of xslt1.decimal-format.attlist -->]]>


<!-- end of xslt1-expression.mod -->
