<!-- ...................................................................... -->
<!-- XSL Transformations 1 Common Attributes Module ....................... -->
<!-- file: xslt1-attribs.mod
     
     XSLT, XSL Trensformations, Version 1.0
     
     Copyright 2010 Wakaba <w@suika.fam.cx>, All Rights Reserved.
     
     Permission to use, copy, modify and distribute this DTD and its
     accompanying documentation for any purpose and without fee is hereby
     granted in perpetuity, provided that the above copyright notice and
     this paragraph appear in all copies.  The copyright holders make no
     representation about the suitability of the DTD for any purpose.
     
     It is provided "as is" without expressed or implied warranty.
     
     Revision: 2010-06-20T04:26:01+00:00 (Generated by mkdtds/1.7)
     
     This DTD module is identified by the SYSTEM identifier:
     
       SYSTEM "xslt1-attribs.mod"
     
     ...................................................................... -->

<!-- Common Attributes

     This module declares many of the common attributes.
-->

<!ENTITY % xslt1.common.extra.attrib "">

<!ENTITY % xslt1.disable-output-escaping.attrib
	'disable-output-escaping	%xslt1.yesno.datatype;	"no"'>

<!ENTITY % xslt1.id.attrib
	"id	ID	#IMPLIED">

<!ENTITY % xslt1.mode.attrib
	"mode	%xslt1.qname.datatype;	#IMPLIED">

<!ENTITY % xslt1.space.attrib
	"xml:space	(default|preserve)	#IMPLIED">

<!ENTITY % xslt1.use-attribute-sets.attrib
	"use-attribute-sets	%xslt1.qnames.datatype;	#IMPLIED">

<!ENTITY % xslt1.extension-element-prefixes.attrib
	"extension-element-prefixes	%xslt1.tokens.datatype;	#IMPLIED">

<!ENTITY % xslt1.exclude-result-prefixes.attrib
	"exclude-result-prefixes	%xslt1.tokens.datatype;	#IMPLIED">

<!ENTITY % xslt1.common.attrib
	"%xslt1.common.extra.attrib;
	%xslt1.xmlns.attrib;">


<!-- end of xslt1-attribs.mod -->
