<!-- ...................................................................... -->
<!-- Hypertext Markup Language Non-Standard Elements and Attributes
             Datatypes Module ............................................. -->
<!-- file: html-non-standard-datatype.mod
     

     
     Copyright 2005 Wakaba <wakaba@suikawiki.org>, All Rights Reserved.
     
     Permission to use, copy, modify and distribute this DTD and its
     accompanying documentation for any purpose and without fee is hereby
     granted in perpetuity, provided that the above copyright notice and
     this paragraph appear in all copies.  The copyright holders make no
     representation about the suitability of the DTD for any purpose.
     
     It is provided "as is" without expressed or implied warranty.
     
     Revision: 2005-04-05T01:46:49+00:00 (Generated by mkdtds/1.06)

     R4.9.18  URLs updated.
     
     This DTD module is identified by the SYSTEM identifier:
     
       SYSTEM "https://suika.suikawiki.org/gate/cvs/*checkout*/markup/html/dtd/html-non-standard-datatype.mod"
     
     ...................................................................... -->

<!-- Datatypes

     This module defines containers for the datatypes.
-->

<!-- Input format specification
     <http://www.au.kddi.com/ezfactory/tec/spec/wap_tag1.html#tag2> -->
<!ENTITY % html-non-standard.au.format.datatype "CDATA">

<!-- Icon name <http://www.au.kddi.com/ezfactory/tec/spec/3.html> -->
<!ENTITY % html-non-standard.au.iconname.datatype "NMTOKEN">

<!-- "1" / "2" / "3" / "4" -->
<!ENTITY % html-non-standard.istyle.datatype "NMTOKEN">

<!-- 'infinite' / 1*DIGIT -->
<!ENTITY % html-non-standard.loop.datatype "CDATA">

<!-- IETF Language Tag or empty string (See XML 1.0 SE Errata) -->
<!ENTITY % LanguageCode.datatype "CDATA">

<!ENTITY % html-non-standard.truefalse.datatype "(true|false)">

<!-- URI Reference -->
<!ENTITY % URI.datatype "CDATA">

<!ENTITY % html-non-standard.yesno.datatype "(yes|no)">


<!-- end of html-non-standard-datatype.mod -->
