<!-- ...................................................................... -->
<!-- Hypertext Markup Language 3.0 (draft 00) Datatypes Module ............ -->
<!-- file: html30-00-datatype.mod
     

     
     Copyright 2005 Wakaba <w@suika.fam.cx>, All Rights Reserved.
     
     Permission to use, copy, modify and distribute this DTD and its
     accompanying documentation for any purpose and without fee is hereby
     granted in perpetuity, provided that the above copyright notice and
     this paragraph appear in all copies.  The copyright holders make no
     representation about the suitability of the DTD for any purpose.
     
     It is provided "as is" without expressed or implied warranty.
     
     Revision: 2005-04-05T01:46:48+00:00 (Generated by mkdtds/1.06)
     
     This DTD module is identified by the SYSTEM identifier:
     
       SYSTEM "http://suika.fam.cx/www/markup/html/dtd/module/html30-00-datatype.mod"
     
     ...................................................................... -->

<!-- Datatypes

     This module defines containers for the datatypes.
-->

<!-- A space-separated list of SGML NAME tokens.  By convention, the 
     class names are interpreted hierarchically, with the most 
     general class at the first and the most specific at the last,
     where classes are separated by a period. -->
<!ENTITY % html30-00.classes.datatype "NMTOKENS">

<!-- (left|right|all|<number> <unit>) -->
<!ENTITY % html30-00.clear.datatype "NMTOKENS">

<!-- HTML 3.0 Unique Identifiers -->
<!ENTITY % html30-00.id.datatype "ID">

<!-- A two letter language code from ISO 639, optionally followed 
     by a period and a two letter country code from ISO 3166. -->
<!ENTITY % html30-00.LanguageCode.datatype "CDATA">

<!-- IETF Language Tag or empty string (See XML 1.0 TE) -->
<!ENTITY % LanguageCode.datatype "CDATA">

<!-- MD5 checksum -->
<!ENTITY % html30-00.md5.datatype "CDATA">

<!-- SGML.NUMBER -->
<!ENTITY % html30-00.NUMBER.datatype "NMTOKEN">

<!-- URI Reference -->
<!ENTITY % URI.datatype "CDATA">


<!-- end of html30-00-datatype.mod -->
