<!-- ...................................................................... -->
<!-- Hypertext Markup Language Non-Standard Elements and Attributes
             Form Module .................................................. -->
<!-- file: html-non-standard-form.mod
     

     
     Copyright 2005 Wakaba <w@suika.fam.cx>, All Rights Reserved.
     
     Permission to use, copy, modify and distribute this DTD and its
     accompanying documentation for any purpose and without fee is hereby
     granted in perpetuity, provided that the above copyright notice and
     this paragraph appear in all copies.  The copyright holders make no
     representation about the suitability of the DTD for any purpose.
     
     It is provided "as is" without expressed or implied warranty.
     
     Revision: 2005-04-05T01:46:49+00:00 (Generated by mkdtds/1.06)
     
     This DTD module is identified by the SYSTEM identifier:
     
       SYSTEM "http://suika.fam.cx/gate/cvs/*checkout*/markup/html/dtd/html-non-standard-form.mod"
     
     ...................................................................... -->

<!-- Form


-->

<!ENTITY % html-non-standard.input.au.attlist "INCLUDE">
<![%html-non-standard.input.au.attlist;[
<!ATTLIST %input.qname;
	%html-non-standard.emptyok.attribute.qname;	%html-non-standard.truefalse.datatype;	#IMPLIED
	%html-non-standard.format.attrib;>
<!-- end of html-non-standard.input.au.attlist -->]]>

<!ENTITY % html-non-standard.input.istyle.attlist "INCLUDE">
<![%html-non-standard.input.istyle.attlist;[
<!ATTLIST %input.qname;
	%html-non-standard.istyle.attrib;>
<!-- end of html-non-standard.input.istyle.attlist -->]]>

<!ENTITY % html-non-standard.textarea.au.attlist "INCLUDE">
<![%html-non-standard.textarea.au.attlist;[
<!ATTLIST %textarea.qname;
	%html-non-standard.format.attrib;>
<!-- end of html-non-standard.textarea.au.attlist -->]]>

<!ENTITY % html-non-standard.textarea.istyle.attlist "INCLUDE">
<![%html-non-standard.textarea.istyle.attlist;[
<!ATTLIST %textarea.qname;
	%html-non-standard.istyle.attrib;>
<!-- end of html-non-standard.textarea.istyle.attlist -->]]>


<!-- end of html-non-standard-form.mod -->
