<!-- ...................................................................... -->
<!-- Hypertext Markup Language 3.0 (draft 00) Common Attributes Module .... -->
<!-- file: html30-00-attribs.mod
     

     
     Copyright 2005 Wakaba <wakaba@suikawiki.org>, All Rights Reserved.
     
     Permission to use, copy, modify and distribute this DTD and its
     accompanying documentation for any purpose and without fee is hereby
     granted in perpetuity, provided that the above copyright notice and
     this paragraph appear in all copies.  The copyright holders make no
     representation about the suitability of the DTD for any purpose.
     
     It is provided "as is" without expressed or implied warranty.
     
     Revision: 2005-04-05T01:46:48+00:00 (Generated by mkdtds/1.06)
     
     R4.9.18  URLs updated.

     This DTD module is identified by the SYSTEM identifier:
     
       SYSTEM "https://suika.suikawiki.org/www/markup/html/dtd/module/html30-00-attribs.mod"
     
     ...................................................................... -->

<!-- Common Attributes

     This module declares many of the common attributes.
-->

<!ENTITY % html30-00.common.extra.attrib "">

<!ENTITY % html30-00.common.attrib
	"%html30-00.common.extra.attrib;
	%html30-00.xmlns.attrib;
	xml:base	%URI.datatype;	#IMPLIED
	xml:lang	%LanguageCode.datatype;	#IMPLIED
	xml:space	(default|preserve)	#IMPLIED">

<!ENTITY % html30-00.block.align.attrib
	'align	(bleedleft|left|center|right|bleedright|justify)	"center"'>

<!ENTITY % html30-00.class.attrib
	"class	%html30-00.classes.datatype;	#IMPLIED">

<!ENTITY % html30-00.id.attrib
	"id	%html30-00.id.datatype;	#IMPLIED">

<!-- a URI for processing image clicks and drags -->
<!ENTITY % html30-00.imagemap.attrib
	"imagemap	%URI.datatype;	#IMPLIED">

<!ENTITY % html30-00.lang.attrib
	"lang	%html30-00.LanguageCode.datatype;	#IMPLIED">

<!ENTITY % html30-00.Size.attrib
	'width	%html30-00.NUMBER.datatype;	#IMPLIED
	height	%html30-00.NUMBER.datatype;	#IMPLIED
	units	(en|pixels)	"pixels"'>

<!ENTITY % html30-00.src.attrib
	"src	%URI.datatype;	#IMPLIED">

<!ENTITY % html30-00.src.required.attrib
	"src	%URI.datatype;	#REQUIRED">

<!ENTITY % html30-00.attrs.attrib
	"%html30-00.id.attrib;
	%html30-00.lang.attrib;
	%html30-00.class.attrib;">

<!-- Attributes for controlling text flow -->
<!ENTITY % html30-00.needs.attrib
	"clear	%html30-00.clear.datatype;	#IMPLIED">

<!-- Attributes associated with URL based links -->
<!ENTITY % html30-00.url.link.attrib
	"md	%html30-00.md5.datatype;	#IMPLIED">


<!-- end of html30-00-attribs.mod -->
