<!-- ...................................................................... -->
<!-- Hypertext Markup Language 3.0 (draft 00) List Module ................. -->
<!-- file: html30-00-list.mod
     

     
     Copyright 2005 Wakaba <wakaba@suikawiki.org>, All Rights Reserved.
     
     Permission to use, copy, modify and distribute this DTD and its
     accompanying documentation for any purpose and without fee is hereby
     granted in perpetuity, provided that the above copyright notice and
     this paragraph appear in all copies.  The copyright holders make no
     representation about the suitability of the DTD for any purpose.
     
     It is provided "as is" without expressed or implied warranty.
     
     Revision: 2005-04-05T01:46:48+00:00 (Generated by mkdtds/1.06)
     
     R4.9.18  URLs updated.

     This DTD module is identified by the SYSTEM identifier:
     
       SYSTEM "https://suika.suikawiki.org/www/markup/html/dtd/module/html30-00-list.mod"
     
     ...................................................................... -->

<!-- List

       lh

     This module declares the list-oriented element types
     and their attributes.
-->

<!-- lh: a title for a list ............................ -->

<!ENTITY % html30-00.lh.element "INCLUDE">
<![%html30-00.lh.element;[
<!ENTITY % html30-00.lh.content "%html30-00.text.content;">
<!ENTITY % html30-00.lh.qname "lh">
<!ENTITY % html30-00.lh.tagmin.start "-">
<!ENTITY % html30-00.lh.tagmin.end "-">
<![%sgml.tag.minimizable;[
<!ENTITY % html30-00.lh.tagmin "%html30-00.lh.tagmin.start; %html30-00.lh.tagmin.end;">
<!-- end of sgml.tag.minimizable -->]]>
<!ENTITY % html30-00.lh.tagmin "">
<!ELEMENT %html30-00.lh.qname; %html30-00.lh.tagmin; %html30-00.lh.content;>
<!-- end of html30-00.lh.element -->]]>

<!ENTITY % html30-00.lh.attlist "INCLUDE">
<![%html30-00.lh.attlist;[
<!ATTLIST %html30-00.lh.qname;
	%html30-00.attrs.attrib;
	%html30-00.common.attrib;>
<!-- end of html30-00.lh.attlist -->]]>


<!-- end of html30-00-list.mod -->
