<!-- ...................................................................... -->
<!-- Web Forms 2.0 Call For Comments - 27 June 2004
             Common Attributes Module ..................................... -->
<!-- file: webforms20-attribs.mod
     
     Web Forms 2.0, the next generation HTML form model.
     
     Copyright 2005 Wakaba <w@suika.fam.cx>, All Rights Reserved.
     
     Permission to use, copy, modify and distribute this DTD and its
     accompanying documentation for any purpose and without fee is hereby
     granted in perpetuity, provided that the above copyright notice and
     this paragraph appear in all copies.  The copyright holders make no
     representation about the suitability of the DTD for any purpose.
     
     It is provided "as is" without expressed or implied warranty.
     
     Revision: 2005-04-05T01:46:48+00:00 (Generated by mkdtds/1.06)
     
     This DTD module is identified by the SYSTEM identifier:
     
       SYSTEM "webforms20-attribs.mod"
     
     ...................................................................... -->

<!-- Common Attributes

     This module declares many of the common attributes.
-->

<!ENTITY % webforms20.common.extra.attrib "">

<!ENTITY % webforms20.accept.attrib
	"accept	%ContentTypes.datatype;	#IMPLIED">

<!ENTITY % webforms20.accesskey.attrib
	"accesskey	%Character.datatype;	#IMPLIED">

<!ENTITY % webforms20.action.attrib
	"action	%URI.datatype;	#IMPLIED
	enctype	%ContentType.datatype;	#IMPLIED
	method	(get|post|put|delete)	#IMPLIED
	replace	(document|values)	#IMPLIED">

<!ENTITY % webforms20.autocomplete.attrib
	'autocomplete	(on|off)	"on"'>

<!ENTITY % webforms20.autofocus.attrib
	"autofocus	(autofocus)	#IMPLIED">

<!ENTITY % webforms20.disabled.attrib
	"disabled	(disabled)	#IMPLIED">

<!ENTITY % webforms20.form.attrib
	"form	IDREF	#IMPLIED">

<!ENTITY % webforms20.help.attrib
	"help	%URI.datatype;	#IMPLIED">

<!ENTITY % webforms20.img.attrib
	"alt	%Text.datatype;	#IMPLIED
	src	%URI.datatype;	#IMPLIED">

<!ENTITY % webforms20.name.attrib
	"name	CDATA	#IMPLIED">

<!ENTITY % webforms20.size.attrib
	"size	%Number.datatype;	#IMPLIED">

<!ENTITY % webforms20.tabindex.attrib
	"tabindex	%Number.datatype;	#IMPLIED">

<!ENTITY % webforms20.template.attrib
	"template	IDREF	#IMPLIED">

<!ENTITY % webforms20.text.attrib
	"%webforms20.autocomplete.attrib;
	inputmode	CDATA	#IMPLIED
	maxlength	%Number.datatype;	#IMPLIED
	readonly	(readonly)	#IMPLIED">

<!ENTITY % webforms20.value.attrib
	"value	CDATA	#IMPLIED">

<!ENTITY % webforms20.focus.attrib
	"%webforms20.accesskey.attrib;
	%webforms20.autofocus.attrib;
	%webforms20.tabindex.attrib;">

<!-- For non-XHTML 1 namespace element types -->
<!ENTITY % webforms20.repeat.global.attrib
	"%webforms20.repeat.attrib.qname;	CDATA	#IMPLIED
	%webforms20.repeat-start.attrib.qname;	%Number.datatype;	#IMPLIED
	%webforms20.repeat-min.attrib.qname;	%Number.datatype;	#IMPLIED
	%webforms20.repeat-max.attrib.qname;	%Number.datatype;	#IMPLIED">

<!-- For XHTML 1 namespace element types -->
<!ENTITY % webforms20.repeat.attrib
	"repeat	CDATA	#IMPLIED
	repeat-start	%Number.datatype;	#IMPLIED
	repeat-min	%Number.datatype;	#IMPLIED
	repeat-max	%Number.datatype;	#IMPLIED">

<!ENTITY % webforms20.control.extra.attrib
	"">

<!-- Placeholder for additional events attributes -->
<!ENTITY % webforms20.control.events.attrib
	"">

<!ENTITY % webforms20.control.attrib
	"%webforms20.control.extra.attrib;">

<!ENTITY % Common.extra.attrib
	"">

<!ENTITY % Common.attrib
	"%Common.extra.attrib;
	%webforms20.repeat.attrib;">

<!ENTITY % webforms20.common.attrib
	"%webforms20.common.extra.attrib;
	%webforms20.xmlns.attrib;
	%Common.attrib;">


<!-- end of webforms20-attribs.mod -->
