<!-- ...................................................................... -->
<!-- Web Forms 2.0 Call For Comments - 27 June 2004 Frame Target Module ... -->
<!-- file: webforms20-target.mod
     
     Web Forms 2.0, the next generation HTML form model.
     
     Copyright 2005 Wakaba <w@suika.fam.cx>, All Rights Reserved.
     
     Permission to use, copy, modify and distribute this DTD and its
     accompanying documentation for any purpose and without fee is hereby
     granted in perpetuity, provided that the above copyright notice and
     this paragraph appear in all copies.  The copyright holders make no
     representation about the suitability of the DTD for any purpose.
     
     It is provided "as is" without expressed or implied warranty.
     
     Revision: 2005-04-05T01:46:48+00:00 (Generated by mkdtds/1.06)
     
     This DTD module is identified by the SYSTEM identifier:
     
       SYSTEM "webforms20-target.mod"
     
     ...................................................................... -->

<!-- Frame Target


-->

<!ENTITY % webforms20..attrib
	"target	%FrameTarget.datatype;	#IMPLIED">


<!-- end of webforms20-target.mod -->
