<!-- ...................................................................... -->
<!-- Web Forms XML Submission 2.0 Call For Comments -- 27 June 2004
             Datatypes Module ............................................. -->
<!-- file: webforms20-submission-datatype.mod
     
     Web Forms 2.0 XML Submission Format (application/x-www-form+xml).
     
     Copyright 2005 Wakaba <w@suika.fam.cx>, All Rights Reserved.
     
     Permission to use, copy, modify and distribute this DTD and its
     accompanying documentation for any purpose and without fee is hereby
     granted in perpetuity, provided that the above copyright notice and
     this paragraph appear in all copies.  The copyright holders make no
     representation about the suitability of the DTD for any purpose.
     
     It is provided "as is" without expressed or implied warranty.
     
     Revision: 2005-04-05T01:46:48+00:00 (Generated by mkdtds/1.06)
     
     This DTD module is identified by the SYSTEM identifier:
     
       SYSTEM "webforms20-submission-datatype.mod"
     
     ...................................................................... -->

<!-- Datatypes

     This module defines containers for the datatypes.
-->

<!-- An Internet Media Type (with optional parameters) -->
<!ENTITY % ContentType.datatype "CDATA">

<!-- A file name -->
<!ENTITY % webforms20-submission.filename.datatype "CDATA">

<!-- A form control name -->
<!ENTITY % webforms20-submission.name.datatype "CDATA">

<!-- An ID in form -->
<!ENTITY % webforms20-submission.idref.datatype "NMTOKEN">

<!ENTITY % webforms20-submission.index.datatype "NMTOKEN">


<!-- end of webforms20-submission-datatype.mod -->
