<!-- ...................................................................... -->
<!-- Web Forms 2.0 Call For Comments - 27 June 2004 Datatypes Module ...... -->
<!-- file: webforms20-datatype.mod
     
     Web Forms 2.0, the next generation HTML form model.
     
     Copyright 2005 Wakaba <w@suika.fam.cx>, All Rights Reserved.
     
     Permission to use, copy, modify and distribute this DTD and its
     accompanying documentation for any purpose and without fee is hereby
     granted in perpetuity, provided that the above copyright notice and
     this paragraph appear in all copies.  The copyright holders make no
     representation about the suitability of the DTD for any purpose.
     
     It is provided "as is" without expressed or implied warranty.
     
     Revision: 2005-04-05T01:46:48+00:00 (Generated by mkdtds/1.06)
     
     This DTD module is identified by the SYSTEM identifier:
     
       SYSTEM "webforms20-datatype.mod"
     
     ...................................................................... -->

<!-- Datatypes

     This module defines containers for the datatypes.
-->

<!-- An XML Char -->
<!ENTITY % Character.datatype "CDATA">

<!-- A white space separated list of IANA charset names -->
<!ENTITY % Charsets.datatype "CDATA">

<!-- An Internet Media Type -->
<!ENTITY % ContentType.datatype "CDATA">

<!ENTITY % ContentTypes.datatype "CDATA">

<!-- Target frame or window name -->
<!ENTITY % FrameTarget.datatype "NMTOKEN">

<!-- A non-negative integer -->
<!ENTITY % Number.datatype "NMTOKEN">

<!-- Script code -->
<!ENTITY % Script.datatype "CDATA">

<!-- A human readable text -->
<!ENTITY % Text.datatype "CDATA">

<!-- A URI reference -->
<!ENTITY % URI.datatype "CDATA">


<!-- end of webforms20-datatype.mod -->
