<!-- ...................................................................... -->
<!-- Tree Data Module ..................................................... -->
<!-- file: tree-data.mod
     
     This is a markup vocabulary for trees, as defined by 564
     <http://pc5.2ch.net/test/read.cgi/hp/1101043958/564>.
     
     Copyright 2010 Wakaba <w@suika.fam.cx>, All Rights Reserved.
     
     Permission to use, copy, modify and distribute this DTD and its
     accompanying documentation for any purpose and without fee is hereby
     granted in perpetuity, provided that the above copyright notice and
     this paragraph appear in all copies.  The copyright holders make no
     representation about the suitability of the DTD for any purpose.
     
     It is provided "as is" without expressed or implied warranty.
     
     Revision: 2010-06-20T04:57:39+00:00 (Generated by mkdtds/1.7)
     
     This DTD module is identified by the SYSTEM identifier:
     
       SYSTEM "http://suika.fam.cx/www/markup/2004/tree/schema/tree-data.mod"
     
     ...................................................................... -->

<!-- Data

       content
-->

<!-- content ........................................... -->

<!ENTITY % tree.content.element "INCLUDE">
<![%tree.content.element;[
<!ENTITY % tree.content.content "%tree.ANY.qname;">
<!ENTITY % tree.content.qname "content">
<!ENTITY % tree.content.tagmin.start "-">
<!ENTITY % tree.content.tagmin.end "-">
<![%sgml.tag.minimizable;[
<!ENTITY % tree.content.tagmin "%tree.content.tagmin.start; %tree.content.tagmin.end;">
<!-- end of sgml.tag.minimizable -->]]>
<!ENTITY % tree.content.tagmin "">
<!ELEMENT %tree.content.qname; %tree.content.tagmin; %tree.content.content;>
<!-- end of tree.content.element -->]]>

<!ENTITY % tree.content.attlist "INCLUDE">
<![%tree.content.attlist;[
<!ATTLIST %tree.content.qname;
	%tree.common.attrib;>
<!-- end of tree.content.attlist -->]]>


<!-- end of tree-data.mod -->
