<!-- ...................................................................... -->
<!-- PrezArk Vocabulary Datatypes Module .................................. -->
<!-- file: prezarc-datatype.mod
     
     PrezArk markup vocabulary, as described in <http://www.justsystem.co.jp/ark/genba/06.html>.
     
     Copyright 2010 Wakaba <w@suika.fam.cx>, All Rights Reserved.
     
     Permission to use, copy, modify and distribute this DTD and its
     accompanying documentation for any purpose and without fee is hereby
     granted in perpetuity, provided that the above copyright notice and
     this paragraph appear in all copies.  The copyright holders make no
     representation about the suitability of the DTD for any purpose.
     
     It is provided "as is" without expressed or implied warranty.
     
     Revision: 2010-06-20T04:53:58+00:00 (Generated by mkdtds/1.7)
     
     This DTD module is identified by the SYSTEM identifier:
     
       SYSTEM "data:,prezarc/prezarc-datatype.mod"
     
     ...................................................................... -->

<!-- Datatypes

     This module defines containers for the datatypes.
-->

<!-- Show or hide in nth personalized view. -->
<!ENTITY % prezarc.bitvector.datatype "NMTOKEN">

<!-- Effect name (extensible). -->
<!ENTITY % prezarc.effect.datatype "NMTOKEN">

<!-- URI. -->
<!ENTITY % prezarc.URI.datatype "CDATA">

<!-- MM:SS subclock. -->
<!ENTITY % prezarc.MMSS.datatype "NMTOKEN">

<!-- CSS-like semicolon-delimited name-value pairs. -->
<!ENTITY % prezarc.props.datatype "CDATA">


<!-- end of prezarc-datatype.mod -->
