<!-- ...................................................................... -->
<!-- SSML 1 Common Attributes Module ...................................... -->
<!-- file: ssml1-attribs.mod
     
     This is Speech Synthesis Markup Language (SSML), Version 1.
     
     Copyright 2004 Wakaba <wakaba@suikawiki.org>, All Rights Reserved.
     
     Permission to use, copy, modify and distribute this DTD and its
     accompanying documentation for any purpose and without fee is hereby
     granted in perpetuity, provided that the above copyright notice and
     this paragraph appear in all copies.  The copyright holders make no
     representation about the suitability of the DTD for any purpose.
     
     It is provided "as is" without expressed or implied warranty.
     
     Revision: 2004-09-16T04:03:38+00:00 (Generated by mkdtds/1.06)
     
     R4.9.18  URLs updated.

     This DTD module is identified by the SYSTEM identifier:
     
       SYSTEM "https://suika.suikawiki.org/www/markup/voice/schema/module/ssml1-attribs.mod"
     
     ...................................................................... -->

<!-- Common Attributes

     This module declares many of the common attributes.
-->

<!ENTITY % ssml1.common.extra.attrib "">

<!ENTITY % ssml1.common.attrib
	"%ssml1.common.extra.attrib;
	%ssml1.xmlns.attrib;">


<!-- end of ssml1-attribs.mod -->
