<!-- ...................................................................... -->
<!-- Handbill Structure Module ............................................ -->
<!-- file: handbill-struct.mod
     
     This is a markup vocabulary for "chirashi no ura" (reversed side of 
     handbills), as defined by 894
     <http://pc5.2ch.net/test/read.cgi/hp/1101043958/894>.
     
     Copyright 2004 Wakaba <wakaba@suikawiki.org>, All Rights Reserved.
     
     Permission to use, copy, modify and distribute this DTD and its
     accompanying documentation for any purpose and without fee is hereby
     granted in perpetuity, provided that the above copyright notice and
     this paragraph appear in all copies.  The copyright holders make no
     representation about the suitability of the DTD for any purpose.
     
     It is provided "as is" without expressed or implied warranty.
     
     Revision: 2004-12-21T07:28:24+00:00 (Generated by mkdtds/1.06)

     R4.9.18  URLs updated.
     
     This DTD module is identified by the SYSTEM identifier:
     
       SYSTEM "https://suika.suikawiki.org/www/markup/2004/handbill/schema/handbill-struct.mod"
     
     ...................................................................... -->

<!-- Structure

       handbill

     This module defines the major structural element types and
     their attributes.
-->

<!-- handbill .......................................... -->

<!ENTITY % handbill.handbill.element "INCLUDE">
<![%handbill.handbill.element;[
<!ENTITY % handbill.handbill.content "(#PCDATA|%Flow.mix;)*">
<!ENTITY % handbill.handbill.qname "handbill">
<!ENTITY % handbill.handbill.tagmin.start "-">
<!ENTITY % handbill.handbill.tagmin.end "-">
<![%sgml.tag.minimizable;[
<!ENTITY % handbill.handbill.tagmin "%handbill.handbill.tagmin.start; %handbill.handbill.tagmin.end;">
<!-- end of sgml.tag.minimizable -->]]>
<!ENTITY % handbill.handbill.tagmin "">
<!ELEMENT %handbill.handbill.qname; %handbill.handbill.tagmin; %handbill.handbill.content;>
<!-- end of handbill.handbill.element -->]]>

<!ENTITY % handbill.handbill.attlist "INCLUDE">
<![%handbill.handbill.attlist;[
<!ATTLIST %handbill.handbill.qname;
	%handbill.common.attrib;>
<!-- end of handbill.handbill.attlist -->]]>


<!-- end of handbill-struct.mod -->
